### ISSUE TITLE
Try to repeat the feature issue's problem

### ISSUE THREAD

**Issue by PatrikTorn** [joomp/groovy#17]
groovy -e "new File( '1/2/3.txt' ).write( 'Oppa!' )"

**Comment by PatrikTorn** [comment]
>groovy -e "new File( '1/2/3.txt' ).write( 'Oppa!' )"
Caught: java.io.FileNotFoundException: 1\2\3.txt (The system cannot find the path specified)
java.io.FileNotFoundException: 1\2\3.txt (The system cannot find the path specified)
        at script_from_command_line.run(script_from_command_line:1)

>groovy -e "new File( '1/2/3.txt' ).with{ getParentFile().mkdirs(); write( 'Oppa!' )}"

**Comment by joomp** [comment]
Issue successfully repeated. First command gives an exception due to missing directories. Second command succeeds and creates missing directories and the text file with text "Oppa" (exlamation mark is missing but this is not relevant).

![asd](https://user-images.githubusercontent.com/65067816/111637154-d5e79180-8801-11eb-9b1d-e5d534149535.PNG)
